name: Build a docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:    
    runs-on: self-hosted
    container: docker:27.0.3

    services:
      docker-dind:
        image: docker:27.0.3-dind

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag test:$(date +%s)
